#@TYPE: Machine
#@NAME: Luckfox Lyra
#@DESCRIPTION: Luckfox Lyra
#https://www.luckfox.com/Luckfox-Lyra-Plus

require conf/machine/include/common.inc
require conf/machine/include/rk3506.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-torvalds-next"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"

UBOOT_MACHINE = "rk3506_defconfig"

#TODO: CUSTOM_KERNEL_DEVICETREE = "rockchip/rk3566-radxa-zero-3e.dtb"

IMAGE_FSTYPES = "wic wic.zst tar.zst"
WKS_FILE = "mini_partitions.wks.in"

UBOOT_EXTLINUX_KERNEL_ARGS = "rootwait rw"
UBOOT_EXTLINUX_ROOT = "root=/dev/mmcblk0p${bootpart}"
