# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-beaver"
BBFILE_PATTERN_meta-beaver = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-beaver = "12"

LAYERDEPENDS_meta-beaver = "core swupdate"
LAYERSERIES_COMPAT_meta-beaver = "scarthgap styhead walnascar whinlatter"

BBFILES_DYNAMIC += " \
    meta-radxa:${LAYERDIR}/dynamic-layers/meta-radxa/*/*/*.bb \
    meta-radxa:${LAYERDIR}/dynamic-layers/meta-radxa/*/*/*.bbappend \
    chromium-browser-layer:${LAYERDIR}/dynamic-layers/chromium-browser-layer/*/*/*.bbappend \
"