# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-bober"
BBFILE_PATTERN_meta-bober = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-bober = "12"

LAYERDEPENDS_meta-bober = "core"
LAYERSERIES_COMPAT_meta-bober = "scarthgap"
